### ISSUE TITLE
Blog Feed not found

### ISSUE THREAD

**Issue by w1n5l0w** [mumble-voip/mumble-www#102]
The Blog provides a link to a RSS Feed with URL https://mumble.info/blog/index.xml which doesn't seem to exist. Would be nice to have the feed functioning/available behind the link.

**Comment by Kissaki** [comment]
That should link should point to https://www.mumble.info/blog/index.xml, which works.

**Comment by Kissaki** [comment]
It is fixed now. Thank you for reporting it.
