### ISSUE TITLE
Development snapshots downloads are broken

### ISSUE THREAD

**Issue by ailox** [mumble-voip/mumble-www#103]
**Describe the bug**
https://www.mumble.info/downloads/#development-snapshots links result in "Service unavailable".
https://dl.mumble.info/snapshot/ is empty, https://dl.mumble.info/nightly/ only contains .AppImage files and their signatures.

**Steps to Reproduce**
1. Go to 'https://www.mumble.info/downloads/#development-snapshots'
2. Click on any link
3. See error

**Expected behavior**
The development snapshots should probably be working.

**Desktop (please complete the following information):**
 - Does not apply

**Comment by davidebeatrici** [comment]
The download links are not working because the Go web server is not started.

However, new development snapshots are not available yet.

**Comment by Kissaki** [comment]
@davidebeatrici The Webserver is running. Are those paragraphs/sentences two separate reasons for them not working? The webserver service is running.

Are all previous snapshots dropped?

So we are waiting for a/our first 1.4.0 snapshot for this to be fixed?

**Comment by Krzmbrzl** [comment]
At the moment we don't have any development snapshots. And as it doesn't really make sense to have *old* snapshots laying around I **suspect** that Davide has dropped them in the spring-clean he performed

**Comment by davidebeatrici** [comment]
I moved all snapshots under the `archive` folder, but thought the issue was caused by the Go web server due to the error being "Service unavailable".

**Comment by Kissaki** [comment]
Any ETA for Snapshots?

If it is several days/more than a week I suggest we remove the section/replace the download links with a notice on the website.

**Comment by Krzmbrzl** [comment]
It'll probably take more than a couple of days, so removing the download link until then is probably a good idea
