### ISSUE TITLE
Add a page for our sponsors

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble-www#104]
On our previous homepage (https://wiki.mumble.info) we put a logo for each sponsor at the bottom of the page.

What we should do, instead, is add a dedicated page on the website, ideally with a description for each sponsor.

**Comment by Krzmbrzl** [comment]
These issues are completely unrelated and should be 2 separate issues.
Having a dedicated sponsor page sounds like a good idea though

**Comment by davidebeatrici** [comment]
Opened a separate issue: #105
