### ISSUE TITLE
Thumbnail image for wiki pages is wrong

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble-www#105]
When a link to a page on our wiki is sent on Matrix, the thumbnail is [Backtrace](https://backtrace.io)'s logo instead of ours.

![](https://user-images.githubusercontent.com/5897523/88487584-d5566e00-cf86-11ea-9405-f210c2106255.png)

This probably happens because we don't explicitly set the `og:image` attribute.

There's an extension that appears to fix this: https://www.mediawiki.org/wiki/Extension:OpenGraphMeta

**Comment by Kissaki** [comment]
Closing because #213 purged the wiki.
