### ISSUE TITLE
3rd Party Applications WiKi still supported?

### ISSUE THREAD

**Issue by hiro2233** [mumble-voip/mumble-www#106]
Hi,

m trying to add a third party project on client and server grid tables, but i see some issues that you are having some problems adding or updating about it, i sent the registration for Hiro2233 account and activated it by email, so my doubt is about if it still supported or not?

Thanks in advance.
Hiroshi.

**Comment by Krzmbrzl** [comment]
So you logged into the wiki and made the changes but the changes aren't showing up on that page?

We had caching issues for the wiki in the past where it would take really long for changes to be reflected on the respective page...

**Comment by hiro2233** [comment]
No, there is another issue, i'm waiting for someone send me the password to email and then logging on the wiki to try add the third party projects, but, if the wiki has problems, so that mean we do nothing.

**Comment by Krzmbrzl** [comment]
Ah so you requested an account that has not been granted yet? Or are you trying to reset the password for your existing account?

**Comment by hiro2233** [comment]
> Ah so you requested an account that has not been granted yet?

This one.

**Comment by Kissaki** [comment]
I checked the approval queue, found the matching name and approved it.

**Comment by hiro2233** [comment]
Thanks.
