### ISSUE TITLE
Stable URLs for latest snapshot/current stable/server/client/android/ios

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble-www#11]
Anyone can use those URLs on his website instead of changing them on every release.

Like this: https://www.natenom.com/getmumble/

**Comment by Natenom** [comment]
The download page #9 could use those stable urls.

**Comment by mkrautz** [comment]
I suppose this requires support from the server-side, to do a redirect?

**Comment by ranomier** [comment]
This is needed so badly. I use Natenoms links right now for my project, but i would rather use an official link.

So many other projects out there have stable links to the latest versions. It would make updates easier.

Examples:

- https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-GB
- http://powdertoy.co.uk/Download/powder-lin64.zip
- https://josm.openstreetmap.de/josm-latest.jar

Sourceforge, as example gnucash:
- https://sourceforge.net/projects/gnucash/files/latest/download?source=files



This is my repo, it is not working yet :).
https://github.com/ranomier/alpine_mumble_mumo_docker

**Comment by bontibon** [comment]
Remaining work completed in 762c89db38f1ac71f8b907f5ba15634340304de5.  Note there is no stable URL for Android, since that is a 3rd party app.

**Comment by ranomier** [comment]
Awesome <3 :3
