### ISSUE TITLE
Third party WiMic Android and WiMic Server/Client added

### ISSUE THREAD

**Issue by hiro2233** [mumble-voip/mumble-www#116]
you may consider add the WiMic Android client Google PlayStore link https://play.google.com/store/apps/details?id=bo.htakey.wimic.

And  you may consider WiMic Server/Client GNU/Linux and Windows (MSYS2) release link on github:
https://github.com/hiro2233/wimic/releases too.

Thanks in advance.

**Comment by Krzmbrzl** [comment]
To me it seems that this project is not (specifically) related to Mumble. Therefore I don't see why it should be listed as a Mumble 3rdParty application :thinking:

**Comment by Kissaki** [comment]
It doesn’t even mention Mumble. I’m confused.

**Comment by hiro2233** [comment]
Sorry about the misunderstood, i will explain the use on mumble servers on the Google PlayStore and releases descriptions too.

**Comment by hiro2233** [comment]
On the server side it's use Murmur protocol, but only receive data from default clients, data transmission and reception is enabled if client is in admin mode.

**Comment by Krzmbrzl** [comment]
I still don't see Mumble being mentioned on the (english) playstore page :eyes:

**Comment by Kissaki** [comment]
I’m still confused. Either way it/server sounds like something for the third party application page, which is currently in the wiki. The main websites downloads page at the moment only lists the most central and decisive options; mainly our official ones where available, and alternatives where we do not provide anything.

Is the server a Mumble server or not?

Do clients list and connect to normal Mumble servers, and list the servers from the public server list?

**Comment by hiro2233** [comment]
> I still don't see Mumble being mentioned on the (english) playstore page eyes

I updated the playstore page english and spanish too, please see again.

> 
I’m still confused. Either way it/server sounds like something for the third party application page, which is currently in the wiki. The main websites downloads page at the moment only lists the most central and decisive options; mainly our official ones where available, and alternatives where we do not provide anything.

Ok, for that reason m asking if wimic server is considered or not a third party mumble server builded with that default options, if not i will remove it from the wiki.

> Is the server a Mumble server or not?

Ok, i will be more specific, wimic server work as a mumble server if you build with macro HALFDUPLEX_SERVER set to 0 and FLAVOUR set to NULL string, by default HALFDUPLEX_SERVER macro is set to 1 and FLAVOUR macro is set to "WiMic".

So, i ask you, is could be considered a third party mumble server or not?

> Do clients list and connect to normal Mumble servers, and list the servers from the public server list?

Yes, can connect to any normal Mumble server, public server list is disabled, you need to enter this manually, i did this for security reasons.

**Comment by Krzmbrzl** [comment]
Our wiki-registration should be working again. Thus you can now add your application to https://wiki.mumble.info/wiki/3rd_Party_Applications yourself :point_up:
