### ISSUE TITLE
Add "secure" to the sub title

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble-www#12]

**Comment by mkrautz** [comment]
Our "slogan" is becoming quite unwieldy... :)

**Comment by Kissaki** [comment]
Where/How would you put it?

I think the current slogan is good enough, and it is long enough already. It's better to feature 'security' on the introductory content and feature list.

Current sub title for reference:

> Open Source, Low Latency, High Quality Voice Chat

**Comment by ranomier** [comment]
I would drop the "High Quality" for "secure".

> Open Source, Low Latency and Secure Voice Chat

The high quality is for many an expected thing. I think ramping up the expectation is a bad thing.

**Comment by Mikaela** [comment]
I think the word secure would nowadays widely imply end-to-end-encryption so I wouldn't advertise it until https://github.com/mumble-voip/mumble/issues/1813 is done.

I am assuming the sub title you are talking about is currently:

> Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.

**Comment by Kissaki** [comment]
Thank you for the suggestions/discussion. Arguments and input much appreciated.

**Comment by Hayden4126** [comment]
I agree with @ranomier, I think replacing high quality with secure would be a good idea.
> Mumble is an open source, low-latency, secure voice chat software primarily intended for use while gaming.

**Comment by Kissaki** [comment]
We will leave it like it is for now. We already list three, four would arguably too much. Secure may be considered an expectation, and may make some users expect true end to end encryption (or transmission).
