### ISSUE TITLE
Add direct link to Github?

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#127]
Some projects have a direct link to their source code repos on their website.

For example directly in the Menu or in the footer section.

**Comment by Krzmbrzl** [comment]
A `Source Code` entry in the menu bar seems like a good thing to have. Should also be rather straight forward to add by modifying https://github.com/mumble-voip/mumble-www/blob/master/hugo/config/_default/menus.toml :point_up:

**Comment by toby63** [comment]
Ok, would you rather like a direct link to github (some sites do this) or a seperate page with a link?

**Comment by Krzmbrzl** [comment]
I don't have any information that I would want to put on that extra page. Therefore I'd vote for a direct link :point_up:

**Comment by toby63** [comment]
Only argument that I can think of is:
Mumble is seperated into different repos, so we might explain that a little bit.

But we could also simply link to the overview page.

**Comment by Krzmbrzl** [comment]
The Source Code of Mumble is not separated though. We also have additional repos for additional projects, but the main source code is a single repo. And that's what we should link to. Otherwise users might be confused as to which project holds the actual source code they're interested in

**Comment by toby63** [comment]
Ok.
