### ISSUE TITLE
Different or no article image

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble-www#13]
I think its too much to have the Mumble logo on the top AND also in every article.

**Comment by mkrautz** [comment]
Is it an article image? Or is it just for blog posts?

The blog posts used this on the "old" blog, too:

http://blog.mumble.info/

**Comment by mkrautz** [comment]
For example:
http://blog.mumble.info/mumble-1-2-19/

**Comment by Natenom** [comment]
Yes, and thats also too much from my point of view.

**Comment by mkrautz** [comment]
I agree
