### ISSUE TITLE
Add a newsbox

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#141]
Just an idea related to #134.

What do you think of adding a newsbox to the home page?
It is like a sidebar showing the latest news, here is an example:
https://www.cmsimple.org/doku/en/?Working_with_CMSimple___Newsboxes

It could show only the most important news, such as releases and security notes etc.

We could maybe implement this, with:
- categories for the blog (so we can differentiate between news and blog posts (e.g. development blog entries (if they ever exist))
- iframe or some other solution for the newsbox, if there is no native solution in hugo

**Comment by Krzmbrzl** [comment]
Featuring the most recent blog post on the main page is probably a nice addition
