### ISSUE TITLE
Create shortcodes to set links to Mumble project websites

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble-www#15]
https://gohugo.io/content-management/shortcodes/

There may be a better way doing this. For example on Wiki systems this is called "interwiki link".

Instead of using 100 times "https://wiki.mumble.info/abc/def" on the blog we can use something like "<mwiki>/abc/def".

When the wiki URL is changed in the future we only need to update the "interwiki link" once.

**Comment by Kissaki** [comment]
Implemented and used in content in branch `shortcode-wiki`.
I would like to wait for move to GitLab for a viewable result for the review. Should make it easier/a better review.
