### ISSUE TITLE
Wiki Mail SMTP client is broken

### ISSUE THREAD

**Issue by nm17** [mumble-voip/mumble-www#154]
Sorry if this is offtopic, but I can't find a better place to report it than here.

```
Error sending mail:

Failed to send data [SMTP: Invalid response code received from server (code: 554, response: Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: Mumble Wiki <noreply-wiki@mumble.info>, noreply-wiki@mumble.info)] 
```

https://wiki.mumble.info/wiki/Special:RequestAccount

**Comment by davidebeatrici** [comment]
This probably happens because we now have proper mail DNS records, for validation.

As a workaround we could either send emails via Amazon's service or run our own SMTP server (as we do for the forums), but I'm not sure it's worth it considering we're going to get rid of the VPS soon.

**Comment by Kissaki** [comment]
I’m a little confused. Did you try to send an email to `noreply-wiki@mumble.info`?

**Comment by nm17** [comment]
> I’m a little confused. Did you try to send an email to `noreply-wiki@mumble.info`?

I was trying to create an account on https://wiki.mumble.info/wiki/Special:RequestAccount

**Comment by Kissaki** [comment]
As per #196, wiki does not receive doc updates, is obsolete, and being replaced. We won't invest in fixing the wiki registration functionality.
