### ISSUE TITLE
Cyberia picture on the sponsors page loads forever

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#162]
https://www.mumble.info/sponsors/

I think the picture could be much smaller in filesize.

OT: Besides that it still looks scary.

**Comment by Krzmbrzl** [comment]
It loads fast for me :eyes:

**Comment by davidebeatrici** [comment]
~850 KB is not a lot for a 1080x1080 PNG image, however we can definitely resize it because we're showing it at 200x200.
