### ISSUE TITLE
Error 503 certificate has expired

### ISSUE THREAD

**Issue by mikenor** [mumble-voip/mumble-www#167]
Cannot access the website. :-(

At https://www.mumble.info/ there is just a Varnish cache error: 503 certificate has expired. The certificate presented to my browser for www.mumble.info is actually fine, but apparently the backend is serving an expired certificate to Varnish.

At https://mumble.info/ there is a different certificate than www.mumble.info. That one expired yesterday. Maybe this is the same certificate that Varnish on www is complaining about.

**Comment by davidebeatrici** [comment]
Yes, indeed.

I'm configuring automatic renewal right now.

**Comment by davidebeatrici** [comment]
Done!
