### ISSUE TITLE
Expired SSL Certificate - Download not working

### ISSUE THREAD

**Issue by moritzuehling** [mumble-voip/mumble-www#176]
Heyo, if I go to

https://www.mumble.info/downloads/

and click on "Windows client (x64)", I get forwarded to https://dl.mumble.info/latest/stable/client-windows-x64

This link replies with a HTTP 503.
<img width="371" alt="image" src="https://user-images.githubusercontent.com/7847742/172347842-21086715-5593-4e9d-bb83-8b9399288796.png">

For anyone else experiencing this, you can still download the official client at: https://github.com/mumble-voip/mumble/releases/latest

But there's probably value in fixing up the website :)

**Comment by davidebeatrici** [comment]
Looks like Apache did not refresh the certificate for all sites...

I restarted the service and everything seems fine now.
