### ISSUE TITLE
Windows installer requirement Visual C++ Redistributable 2015-2022 needs added

### ISSUE THREAD

**Issue by ZeroAbility** [mumble-voip/mumble-www#177]
The following issue was created in the normal repo for the application but requires changes to the downloads section of the website to inform people the must download and install Visual C++ Redistributable 2015-2022:

https://github.com/mumble-voip/mumble/issues/5549

The latest version can be downloaded here:

https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Kissaki** [comment]
Given that we have a mix of x86 x64 with the client supporting overlay for both architectures, do we need both redistributables too?

**Comment by davidebeatrici** [comment]
Yep.
