### ISSUE TITLE
3rd Party Applications: remove mumble-django

### ISSUE THREAD

**Issue by nodiscc** [mumble-voip/mumble-www#189]
Mumble-Django listed at https://wiki.mumble.info/wiki/3rd_Party_Applications#Web-Interfaces cannot be downloaded anymore.
The project at https://bitbucket.org/Svedrin/mumble-django/ was deleted, and all installation/build instructions (including those https://mumble-django.readthedocs.io/en/latest/) do not work anymore.

It should be removed from the list.

The https://wiki.mumble.info/wiki/Mumble-Django page should also be removed.

**Comment by Kissaki** [comment]
Thank you for the heads up

* Looks like there is a fork here https://github.com/UbuntuEvangelist/mumble-django
* GitHub Svedrin account does not host any such repository https://github.com/Svedrin

I removed the wiki page and the web interface and channel viewer entries from the wiki third-party lists

Thanks
