### ISSUE TITLE
Mumble Wiki Registration Broken

### ISSUE THREAD

**Issue by farmergreg** [mumble-voip/mumble-www#196]
I want to add https://github.com/farmergreg/rumble to https://wiki.mumble.info/wiki/3rd_Party_Applications.

So I tried to register for an account on the wiki.
I received this error when trying to start the process to register an account for editing the wiki:

Error sending mail:
Failed to send data [SMTP: Invalid response code received from server (code: 554, response: Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1: Mumble Wiki <noreply-wiki@mumble.info>, noreply-wiki@mumble.info)]

**Comment by farmergreg** [comment]
This appears to be related to #154

**Comment by Kissaki** [comment]
The wiki is deprecated, although the migration of existing docs we want to migrate has not finished yet - our current target for docs is our website. Given the other email issue has not been fixed, I doubt this registration will be fixed either. (Personally I will focus on docs migration over fixing registration of the obsolete/deprecated wiki. And I think the others who could look into it also have other things they prioritize over this.)

**Comment by Kissaki** [comment]
The most important doc was migrated. While there are still a few things open, I am closing this ticket. The wiki is not where we create, update, or maintain documentation anymore. So wiki registration being broken is acceptable. We plan to take it down after concluding the migration of the most important docs.
