### ISSUE TITLE
Rendering artifacts in mumble.svg in Chrome

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-www#2]
![image](https://user-images.githubusercontent.com/36527/37559275-7086893e-2a23-11e8-81de-f871f4790d81.png)

**Comment by mkrautz** [comment]
Note the pointy triangles in the B.

**Comment by bontibon** [comment]
Is the logo being changed (mumble-voip/mumble/issues/2137)?

**Comment by mkrautz** [comment]
No, not immediately. This is our logo for now.
