### ISSUE TITLE
Fatal exception of type InvalidArgumentException

### ISSUE THREAD

**Issue by DominikTV** [mumble-voip/mumble-www#24]
When I try to access "https://www.mumble.info", I get redirected to https://wiki.mumble.info/ and with the following message on the website:

`[98cdf49479bdd8e33a18cfcf] 2018-06-16 19:37:46: Fatal exception of type InvalidArgumentException`

and nothing else. 0 cookies placed.

**Comment by Kissaki** [comment]
The wiki is broken since an upgrade. We are working on resolving the issue.

**Comment by Kissaki** [comment]
This mumble-www project repository is an effort for a new website btw, not the current wiki we have deployed right now.

**Comment by Kissaki** [comment]
It is fixed now
