### ISSUE TITLE
Content for /cookies, /legal

### ISSUE THREAD

**Issue by bontibon** [mumble-voip/mumble-www#26]
Or are these pages necessary?

Someone else needs to make that decision.

**Comment by Kissaki** [comment]
What do you mean? What are you asking or suggesting?

**Comment by bontibon** [comment]
The /cookies and /legal pages are empty. I did not create them, so I don't know what content should be there, or if they need to exist at all.

**Comment by Kissaki** [comment]
It was you who created them in f8fda14a9f3493f88c77684506e6cf9cc23eb5f5 though??

**Comment by Kissaki** [comment]
We can either host a privacy notice on this website for all our services - wiki, forums, mumble. Or we can keep it specific to this website, and make sure the other services provide their own.

I don’t see why we would want a separate cookies page though. That info should go into privacy policy (if at all - as this site uses no cookies).

As for terms - I don’t think we have anything to share there either. License is specific to mumble, and license information is available separately and on install.

**Comment by bontibon** [comment]
It was originally part of @mkrautz's template (https://github.com/mumble-voip/mumble-www/blob/8b1c61a8ff8d8670611f55b46a3b3283e98e0b9e/index.html#L56-L58), so maybe he knows what to do.

**Comment by Kissaki** [comment]
Let’s just drop it.

He created issues for what he deemed missing. There is none for this.
