### ISSUE TITLE
Figure out what to do with LICENSE and AUTHORS permalinks

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-www#3]
Right now we use the permalinks https://www.mumble.info/LICENSE and https://www.mumble.info/AUTHORS in our LICENSE.header, LICENSE, AUTHORS, etc. to point people to an up-to-date LICENSE or list of authors.

Ideally, we would want this to be automated somehow. Already now, we're forgetting to update these files on the live site.

Now that we use Hugo, the "obvious" way would be to just include them statically. But I worry that they'll grow stale.

Can we do something dynamic here?  Obviously, we could write a simple server for our Hugo site, which has dynamic handlers for /LICENSE and /AUTHORS.

Thoughts? /cc @bontibon

**Comment by bontibon** [comment]
Triggering builds covered in #8

**Comment by mkrautz** [comment]
Not sure how this is covered by https://github.com/mumble-voip/mumble-www/issues/8?

Does that mean we want to trigger a build every time we change the LICENSE/AUTHORS? How do we do that?

Some of the benefits of a static site go away if we fetch stuff during the build...

**Comment by Kissaki** [comment]
Reopening because discussion is still open

**Comment by Kissaki** [comment]
I think either triggering PRs automatically (like our translation bot on mumble) or triggering master updates and build+deploy automatically is viable.

Neither AUTHORS nor LICENSE change so often that a static generation is not viable.

**Comment by Kissaki** [comment]
Hugo can pull CSV and JSON data automatically - see [Data-Driven Content on Data Templates](https://gohugo.io/templates/data-templates/#data-driven-content).
