### ISSUE TITLE
Create config management script for production setup

### ISSUE THREAD

**Issue by actown** [mumble-voip/mumble-www#40]
Use Ansible or another config management system to setup the host that will run the website. 

The goal would be to make it easy to stand up the website if the host underneath needs to be recreated.

I don't think this needed for release, but it would be a nice to have.

**Comment by Kissaki** [comment]
We have an internal repository for server configurations for our server boxes. That includes configuration for mumble.info, and one for `test.mumble.info` in a feature branch/merge request.

**Comment by actown** [comment]
Sounds good, closing.
