### ISSUE TITLE
Fix 404 does not serve generated 404.html file

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble-www#49]

**Comment by Kissaki** [comment]
I think this is on the go webserver returning it's own 404 content. How do we configure/implement this?

Is it actually as complicated as it seems?

**Comment by davidebeatrici** [comment]
I confirm that it's the Go webserver serving the 404 page.

Implementing a custom error handler seems very simple: https://stackoverflow.com/a/10001309

**Comment by Kissaki** [comment]
Fixed via Apache site configuration
