### ISSUE TITLE
Set up a form on the website to report issues

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble-www#53]
```
<agris> I do not have a Microsoft/Github account as I do not accept the privacy policy and terms of service. Is there another way to open a ticket?
<davidebeatrici> I understand. Would you like me to open an issue for you?
<agris> If there is no other way, I would appreciate that. However if that is so, would you mind opening another ticket about having a way to contribute without a Microsoft account?
```

**Comment by Mikaela** [comment]
I guess the solution will include [git-format-patch](https://git-scm.com/docs/git-format-patch) assuming they also hope to be able to send PRs without a GitHub account?

**Comment by Kissaki** [comment]
I’m not sure how viable this is.

Most users will be able to use GitHub. And if necessary people can send patches in directly.

An adequate form would have to include a backend or talk to GitHub on other users behalf. Maybe not worth the effort when we have more pressing tasks.
