### ISSUE TITLE
Make the forum link back to the website

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble-www#56]

**Comment by davidebeatrici** [comment]
I set the main website URL to https://mumble.info.

> If specified, a link to this URL will be prepended to your board’s breadcrumbs and the board logo will link to this URL instead of the forum index. An absolute URL is required, e.g. http://www.phpbb.com.

**Comment by Kissaki** [comment]
Uh, in the forums I clicked on the logo - the link was indeed to mumble.info, and it asked for a user certificate.

I’ve seen this multiple times before.

Opening the same link now does not ask for a user certificate. But I guess because I pressed cancel before and it remembers.

And indeed when I open a new private window, it asks again.

Something is broken with that domain HTTP web request and response setup.

**Comment by Kissaki** [comment]
Otherwise looks good. I can see the logo link (was that logo there before?) and the breadcrumb home.

**Comment by davidebeatrici** [comment]
Yes, the logo was there, but it pointed to the forums' homepage.

As for the user certificate: I actually never experienced the issue.

**Comment by Kissaki** [comment]
Extracted issue to #58
