### ISSUE TITLE
Link to protocal-documentation

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble-www#59]
I just found https://mumble-protocol.readthedocs.io/en/latest/index.html which I think should definitely be linked from the mumble-webpage.
I'm not sure if this is already the case (if so, just close this issue), but I wanted to throw this in here anyways :)

**Comment by Kissaki** [comment]
We want to move some documentation from the wiki onto the website. This is tracked in #35.

That would include information about the protocol, and/or a link to those docs.

I’ll close this for now to not get lost in tickets of details of stuff we do not have yet, and consider it part of the more general "move some documentation/documentation entry point onto the website".
