### ISSUE TITLE
Download page is missing AppImage

### ISSUE THREAD

**Issue by probonopd** [mumble-voip/mumble-www#65]
AppImage is available at https://github.com/mumble-voip/mumble/releases but any mention if it is missing on the download page at https://www.mumble.info/downloads/ and in the 1.3.0 release announcement.

**Comment by davidebeatrici** [comment]
AppImage is only available at https://dl.mumble.info/snapshot, we didn't build it for 1.3.

Closing in favor of #64.

**Comment by Kissaki** [comment]
@davidebeatrici You transferred this from the mumble repository. Do we have a ticket to build a 1.3 appimage there then?

**Comment by davidebeatrici** [comment]
We don't.
