### ISSUE TITLE
Figure out how to host the new website

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-www#7]
We'll need to figure out how to host the new website before we can go live.

**Comment by mkrautz** [comment]
This is somewhat related to https://github.com/mumble-voip/mumble-www/issues/3

**Comment by Kissaki** [comment]
For another project I have a running GitLab setup with automatic hugo build, html artifact that can be uploaded to a webserver, automatically pushes to my staging server via sftp with a priv key (`lftp` `mirror --reverse`), and another manually triggerable deploy to production environment.
(It may be possible to get PR-specific-staging to work without cloud hosting/spawning, which I would be excited about, but I have not tried yet.)

As hugo produces static website content there's little in terms of server requirements we need.
The website has guides for various targets https://gohugo.io/hosting-and-deployment/

We will have to configure the webserver with a rewrite rule to handle 404s(?).

What else can hugo/static site not handle and we have to consider on the server side (in contrast to just automatically updating content via hugo)?

**Comment by bontibon** [comment]
I've pushed a WIP Go web server to do the hosting.  Having a purely static site without any special server configuration/handling got messy, specifically around the grumble import path and static URLs for downloads.

**Comment by Kissaki** [comment]
Can we put it on our `mumble.info` box?

Are there arguments against that?
