### ISSUE TITLE
Provide RSS feed for the blog

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble-www#72]
https://gohugo.io/templates/rss

**Comment by Kissaki** [comment]
Already exists

* https://www.mumble.info/index.xml
* https://www.mumble.info/blog/index.xml

**Comment by Kissaki** [comment]
On the blog there’s also a feed link visible at the bottom.

**Comment by davidebeatrici** [comment]
Oh, I totally missed it. What about moving the button at the top of the blog?
