### ISSUE TITLE
QtMumble

### ISSUE THREAD

**Issue by s1090017** [mumble-voip/mumble-www#80]
https://wiki.mumble.info/wiki/BuildingWindows_(deprecated)

Checkout the Mumble Qt git repo to C:\dev\QtMumble:

cd c:\dev
git clone git://gitorious.org/+mumble-developers/qt/mumble-developers-qt.git QtMumble

This git link is invalid. Can anyone could provide valid git link? Thanks.

**Comment by Kissaki** [comment]
You are in the wrong repository. This is for our website, not mumble itself.

As noted in the deprecation notice banner at the top, that documentation is outdated (and kept for archival purpose).

Our current build-env and instructions can be found in the mumble-releng repository.

If you still want that repo, check our group namespace here on github and you can find our Qt fork there.
