### ISSUE TITLE
Public mumble servers list

### ISSUE THREAD

**Issue by rosa2** [mumble-voip/mumble-www#85]
Hello and thanks for your tool, documentation and site

I hope that this is the right place to report my feature request... Sorry if it is not.

I am writing an article on secure tools to communicate and one of them is yours :)
I would like to offer a list of public servers for people that has not the technical skills or the money to install your program in a server, like in Jitsi wiki or other tools that list their public instances where people can add their instance.

https://github.com/jitsi/jitsi-meet/wiki/Jitsi-Meet-Instances
https://ladatano.partidopirata.com.ar/jitsimeter

I am asking around and I got some, but it would very useful that you have it in your site or in a wiki for people without skills or money.
And maybe it already exits and I wasn't able to find it searching.

Thanks a lot again for this tool that allows us to communicate with little cost on ecology :)

**Comment by Kissaki** [comment]
Hello rosa,

when running a server you can register it to our public server list which can be listed in the client connect window.

https://wiki.mumble.info/wiki/Murmur.ini#Server_Registration

Are you trying to cover some other use case than just finding a public server to use?

There is also #17, and #38 which implemented it but was not applied yet.

**Comment by rosa2** [comment]
Thanks @Kissaki 
You are very kind :)

The article is for a collective (not payed) to teach about the possibilities on text/audio/video-conferences thinking in security and privacy. 
I am in several groups where we use Mumble to make meetings in our servers and I think that many people should use Mumble as an ecological alternative to video-conferences, since not always they are necessary :)
Now I will tell to them to register because in Spain there are only two!
You can close the issue, if you want... and for not opening another issue... is there any plan on federation? People sometimes is scared to make public their servers because of overload.

Thanks a lot, I really enjoy your soft! :)

**Comment by Kissaki** [comment]
Not sure what you mean by federation in that context. It is either announced to the public server list or it is not. There is no plan to subdivide registrations. We have categories, namely countries. And there are some feature requests open for more elaborate tagging/describing/categorizing.
