### ISSUE TITLE
Add Downloads page

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-www#9]
We should add a Downloads page to the site.

The front page should include the most obvious download a user would want.
But we should have a separate page as well, to allow people to download specific products.

Such a page should encompass what's currently handled by the wiki's Download and Third Party Applications sections:

![image](https://user-images.githubusercontent.com/36527/37559419-18157df2-2a26-11e8-8ace-6e70b6eccd36.png)

**Comment by bontibon** [comment]
Main navigation should also have a link to the download page

**Comment by mkrautz** [comment]
@bontibon How would you handle downloads for snapshots?

Right now we query the directory containing downloads (the directory that https://dl.mumble.info serves) and figure out which snapshots to link to.

Should we do this at build time?

Should we implement something in a (potential) server frontend that queries dl.mumble.info and caches the result for XX hours?
