### ISSUE TITLE
[Request] Update the website

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#90]
I see some changes in the sources, like:
```
Android 
Mumla
F-Droid
```
in: https://github.com/mumble-voip/mumble-www/blob/master/hugo/content/downloads.md#third-party-clients

But the website(https://www.mumble.info/downloads/) still lists:
```
Android 
Plumble
Google Play
F-Droid
```

So an update would be good.

**Comment by Kissaki** [comment]
We are aware of it

**Comment by Kissaki** [comment]
#34 #8
