### ISSUE TITLE
[Request] Changes for index.html

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#91]
I would like to suggest some changes to the main site of mumble.info:

**Additions:**

* mumble is server-based
This could maybe be stated more prominently.
Also that users are of course able to create their own servers.

**Changes:**

> Extendible through Ice and GRPC protocols 

gRPC is not auto-enabled/-implemented yet.
And it is also buggy.

> but finds good use in many different environments as well.

I don't think everyone understands what that exactly means.
My suggestion, use the word "usecases" instead of environments.

> Administrators appreciate Mumble for being able to **own their and their users data.**

This is not such a good formulation.
It would be better like this:
`You can setup your own server, which will manage all the user data.`
(Not perfect this way, an addition would be to say that no third party is necessary or gets the data)

**Discussible changes:**
* Ice or better most software for it is outdated, so the mentions of that should maybe be reduced or clarified
* In-game Overlay: I am no expert at this, because I don't use it, but the issues indicate numerous problems with it, so maybe you could at least add something like: `partial support for` or `many games support`
* always encrypted communication: while it is true, it creates the impression that End-to-End-encryption is implemented, which is not the case, so I would add `always encrypted communication between server and client (user)`

**Comment by Kissaki** [comment]
c19de714f3a7473278c661982fc326356973ecab
84b79a2f78202174e4db39d1b4e3d4b489b89fad
f8b5400abc6d340e06b3671232badd672fa2b5f5
