### ISSUE TITLE
[Request] Change the Logo for Ubuntu

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#93]
https://www.mumble.info/downloads/ uses a general linux logo (tux) for ubuntu.
Maybe you could use an ubuntu logo instead.

Advantages:
* clear seperation between generic packages (like static server) and distro-specific packages
* no confusion for inexperienced users

See: https://design.ubuntu.com/brand/ubuntu-logo/

**Comment by toby63** [comment]
While I like seeing this implemented :+1:
I still have to say, the symbol seems a bit small to me, in relation to the other symbols.

Maybe you could increase the size?

**Comment by Kissaki** [comment]
Yeah, I noticed it but landed it rather than not changing it for now.

**Comment by toby63** [comment]
It's not that important, just wanted to mention it, so it will not be forgotten.
