### ISSUE TITLE
Consider to delete iOS clients

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#96]
I have a friend who tried your app on iOS and his version was very outdated (1.2.4 according to the server).

So, while I can't check that myself:
1. We can assume that App Store automatically installs the most recent version.
2. I noticed that the versioning is very confusing, but the date is enough to see that its outdated:

| App | Version in App Store | Date
| ----- | ------------------------ | ------ 
| [Mumble](https://apps.apple.com/us/app/mumble/id443472808) | 1.3.1 | Sep 13, 2017
| [Mumblefy](https://apps.apple.com/us/app/mumblefy/id858752232) | 1.3 | 27 Jun 2016

I suggest you to remove both apps from your website at least, and also consider removing your official app from the App Store (until an updated version is available).

I also don't see any call for help, maybe someone would take over the development of the app:
https://github.com/mumble-voip/mumble-iphoneos

**Comment by davidebeatrici** [comment]
The devil is keeping it hostage: 
![666 commits](https://user-images.githubusercontent.com/5897523/83826234-b0a6ee00-a6db-11ea-9f57-fe64eb0df341.png)

Jokes aside, we definitely need an iOS developer if we want to keep the app alive.

@mkrautz is the original developer and, as you can see from the commits, the only one.

Unfortunately he's been very busy lately, basically since the last update for the app.

And yes, the version is very confusing: it refers to the application's version rather than the Mumble protocol's one.

In case it's not clear, Mumblefy is a third-party application.
Replacing our official app with it would be totally fine... if it was open-source and didn't have a rating of 1.7 stars...

**Comment by Kissaki** [comment]
Age does not necessarily indicate obsoleteness or incompleteness. Our protocol did not change. The baseline is still the same.

**Comment by Kissaki** [comment]
> a rating of 1.7 stars

Why do we recommend it when it has such a low rating? That can’t be good.

**Comment by toby63** [comment]
> Age does not necessarily indicate obsoleteness or incompleteness. Our protocol did not change. The baseline is still the same.

I will not discuss software security here once again, you should know better.

> In case it's not clear, Mumblefy is a third-party application.
Replacing our official app with it would be totally fine... if it was open-source and didn't have a rating of 1.7 stars...

It's clear and even if it would be open source, that wouldn't help as it's even older than your app.

> we definitely need an iOS developer if we want to keep the app alive.

I opened an Issue (https://github.com/mumble-voip/mumble-iphoneos/issues/129), maybe someone is interested.

**Comment by Kissaki** [comment]
> 
> 
> > a rating of 1.7 stars
> 
> Why do we recommend it when it has such a low rating? That can’t be good.

I think I misunderstood you? Because I don’t see 1.7 stars but 5 starts with 1 vote on Mumblefy. So what did you mean?

**Comment by toby63** [comment]
> I think I misunderstood you? Because I don’t see 1.7 stars but 5 starts with 1 vote on Mumblefy. So what did you mean?

I see 1.7 stars.
https://apps.apple.com/us/app/mumblefy/id858752232

**Comment by Kissaki** [comment]
When accessing it from our downloads page I get redirected from /us/ to /dk/…

**Comment by Kissaki** [comment]
Link fixed in fdff690c7482e3af9b6baa67061edd7a4078b20f

Link to Mumblefy removed in f7f7736216bd6f525c2e77464be0f2c7f3f78196

For now we will not remove our iOS client as long as we do not have anything better and no reports of blatant issues.

**Comment by toby63** [comment]
> For now we will not remove our iOS client as long as we do not have anything better and no reports of blatant issues.

I assume the ocb2 issue https://github.com/mumble-voip/mumble/issues/4219 could be a problem there as well, to name just one example.
And because of the "wrong" numbering of the iOS version, it can misslead users into believing it is recent and the date is just wrong.

**Comment by toby63** [comment]
You should at least inform users that it is a really outdated version and that it does not even work correctly with newer servers, like my friend experienced.
