### ISSUE TITLE
Add macOS download notice about installation warning (non-signed app)

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble-www#97]
As raised and discussed in https://github.com/mumble-voip/mumble/issues/4263 we should add a notice to the downloads page to prepare users for the expected warning.

**Comment by toby63** [comment]
As @davidebeatrici said, it might not have a warning, as you use mkrautz account to sign the releases, so no notification necessary, except for development builds (and I was told those will only be available for 1.4.0)
https://github.com/mumble-voip/mumble/issues/4263#issuecomment-640297513

**Comment by Kissaki** [comment]
Good catch, the notice should definitely only be on the snapshots section where we do not have our signing logic integrated yet.
