### ISSUE TITLE
Add an About page

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#98]
You might give some information by whom the website is run, who are the developers of mumble and where to find more information.

**Comment by Kissaki** [comment]
The homepage has the main section “About Mumble”.

**Comment by toby63** [comment]
But that does not contain any of the requested information.
In many countrys it would even be a requirement to provide information about who owns and run the website and is responsible for the development of the software.

I think it would be fair and also transparent to at least link to the mumble project on github and say who of you are the active developers.

**Comment by toby63** [comment]
Closed via #128.
